version: '3'
services:
  app:
    container_name: medichat_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - medichat_api
    networks:
      - medichat


  medichat_api:
    image: postgres:latest
    container_name: medi_chat_db
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-docker_pass}
      - POSTGRES_DB=${DB_NAME:-medi_chat_db}
      - DATABASE_HOST=${DB_HOST:-medichat_api}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - medichat

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-live@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-live_password}
    depends_on:
      - medichat_api
    ports:
      - "5050:80"
    networks:
      - medichat
    restart: unless-stopped

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  medichat:
    driver: bridge
